# Generated by Django 3.2.4 on 2021-06-18 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_alter_item_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('F', 'Food'), ('C', 'Clothes'), ('S', 'Shoes'), ('B', 'Books')], max_length=2),
        ),
    ]
